# Generated by Django 5.0.1 on 2024-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testing_count',
            field=models.IntegerField(default=0),
        ),
    ]
