# Generated by Django 5.0.1 on 2024-01-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=32)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('avg_result', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=512)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.category')),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('result', models.FloatField()),
                ('test_time', models.DurationField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.user')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_text', models.CharField(max_length=256)),
                ('is_right', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question')),
            ],
        ),
    ]
