# Generated by Django 5.0.1 on 2024-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
