# Generated by Django 5.0.1 on 2024-03-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_testing_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='test_time',
            field=models.DurationField(null=True),
        ),
        migrations.CreateModel(
            name='TestingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.question')),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testing')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.variant')),
            ],
        ),
    ]
