# Generated by Django 5.0.1 on 2024-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alter_testing_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reference',
            new_name='ref_name',
        ),
        migrations.AddField(
            model_name='question',
            name='ref_url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
